module Evergreen.Migrate.V20 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

--import Evergreen.V19.

import Array
import Dict
import Evergreen.V19.Auth
import Evergreen.V19.Bridge
import Evergreen.V19.Components.Toast
import Evergreen.V19.Event
import Evergreen.V19.ItemPriority
import Evergreen.V19.Layouts.Scaffold
import Evergreen.V19.Main
import Evergreen.V19.Main.Layouts.Model
import Evergreen.V19.Main.Layouts.Msg
import Evergreen.V19.Main.Pages.Model
import Evergreen.V19.Main.Pages.Msg
import Evergreen.V19.Pages.Account
import Evergreen.V19.Pages.Credits
import Evergreen.V19.Pages.Home_
import Evergreen.V19.Pages.List.ImportShared
import Evergreen.V19.Pages.Lists
import Evergreen.V19.Pages.Lists.Create
import Evergreen.V19.Pages.Lists.Edit.ListId_
import Evergreen.V19.Pages.Lists.Id_.CreateItem
import Evergreen.V19.Pages.Lists.ListId_
import Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_
import Evergreen.V19.Pages.Manual
import Evergreen.V19.Pages.NotFound_
import Evergreen.V19.Pages.Settings
import Evergreen.V19.Pages.Setup
import Evergreen.V19.Pages.Setup.Connect
import Evergreen.V19.Pages.Setup.NewAccount
import Evergreen.V19.Pages.SetupKnown
import Evergreen.V19.Pages.Share.ListId_
import Evergreen.V19.Role
import Evergreen.V19.Route.Path
import Evergreen.V19.Shared
import Evergreen.V19.Shared.Model
import Evergreen.V19.Shared.Msg
import Evergreen.V19.SortedEventList
import Evergreen.V19.Sync
import Evergreen.V19.Types
import Evergreen.V19.UserManagement
import Evergreen.V20.Auth
import Evergreen.V20.Bridge
import Evergreen.V20.Components.Toast
import Evergreen.V20.Event
import Evergreen.V20.ItemPriority
import Evergreen.V20.Layouts.Scaffold
import Evergreen.V20.Main
import Evergreen.V20.Main.Layouts.Model
import Evergreen.V20.Main.Layouts.Msg
import Evergreen.V20.Main.Pages.Model
import Evergreen.V20.Main.Pages.Msg
import Evergreen.V20.Pages.Account
import Evergreen.V20.Pages.Admin.Manual
import Evergreen.V20.Pages.Admin.Menu
import Evergreen.V20.Pages.Credits
import Evergreen.V20.Pages.Home_
import Evergreen.V20.Pages.List.ImportShared
import Evergreen.V20.Pages.Lists
import Evergreen.V20.Pages.Lists.Create
import Evergreen.V20.Pages.Lists.Edit.ListId_
import Evergreen.V20.Pages.Lists.Id_.CreateItem
import Evergreen.V20.Pages.Lists.ListId_
import Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_
import Evergreen.V20.Pages.NotFound_
import Evergreen.V20.Pages.Settings
import Evergreen.V20.Pages.Setup
import Evergreen.V20.Pages.Setup.Connect
import Evergreen.V20.Pages.Setup.NewAccount
import Evergreen.V20.Pages.SetupKnown
import Evergreen.V20.Pages.Share.ListId_
import Evergreen.V20.Role
import Evergreen.V20.Route.Path
import Evergreen.V20.Shared
import Evergreen.V20.Shared.Model
import Evergreen.V20.Shared.Msg
import Evergreen.V20.SortedEventList
import Evergreen.V20.Sync
import Evergreen.V20.Types
import Evergreen.V20.UserManagement
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V19.Types.FrontendModel -> ModelMigration Evergreen.V20.Types.FrontendModel Evergreen.V20.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V19.Types.BackendModel -> ModelMigration Evergreen.V20.Types.BackendModel Evergreen.V20.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V19.Types.FrontendMsg -> MsgMigration Evergreen.V20.Types.FrontendMsg Evergreen.V20.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V19.Types.ToBackend -> MsgMigration Evergreen.V20.Types.ToBackend Evergreen.V20.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V19.Types.BackendMsg -> MsgMigration Evergreen.V20.Types.BackendMsg Evergreen.V20.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V19.Types.ToFrontend -> MsgMigration Evergreen.V20.Types.ToFrontend Evergreen.V20.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V19.Types.FrontendModel -> Evergreen.V20.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Main_Model


migrate_Types_FrontendMsg : Evergreen.V19.Types.FrontendMsg -> Evergreen.V20.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Types_ToBackend : Evergreen.V19.Types.ToBackend -> Evergreen.V20.Types.ToBackend
migrate_Types_ToBackend old =
    old |> migrate_Bridge_ToBackend


migrate_Auth_User : Evergreen.V19.Auth.User -> Evergreen.V20.Auth.User
migrate_Auth_User old =
    old |> migrate_Bridge_User


migrate_Bridge_ToBackend : Evergreen.V19.Bridge.ToBackend -> Evergreen.V20.Bridge.ToBackend
migrate_Bridge_ToBackend old =
    case old of
        Evergreen.V19.Bridge.NewUser p0 ->
            Evergreen.V20.Bridge.NewUser (p0 |> migrate_Bridge_User)

        Evergreen.V19.Bridge.ReconnectUser p0 ->
            Evergreen.V20.Bridge.ReconnectUser p0

        Evergreen.V19.Bridge.RequestAdminData ->
            Evergreen.V20.Bridge.NoOp

        Evergreen.V19.Bridge.GenerateSyncCode ->
            Evergreen.V20.Bridge.GenerateSyncCode

        Evergreen.V19.Bridge.EventAdded p0 ->
            Evergreen.V20.Bridge.EventAdded (p0 |> migrate_Event_EventDefinition)

        Evergreen.V19.Bridge.UseSyncCode p0 ->
            Evergreen.V20.Bridge.UseSyncCode p0

        Evergreen.V19.Bridge.RequestNewEvents p0 ->
            Evergreen.V20.Bridge.RequestNewEvents p0

        Evergreen.V19.Bridge.RequestListSubscription p0 ->
            Evergreen.V20.Bridge.RequestListSubscription p0

        Evergreen.V19.Bridge.ReloadAllForAggregate p0 ->
            Evergreen.V20.Bridge.ReloadAllForAggregate p0


migrate_Bridge_User : Evergreen.V19.Bridge.User -> Evergreen.V20.Bridge.User
migrate_Bridge_User old =
    case old of
        Evergreen.V19.Bridge.Unknown ->
            Evergreen.V20.Bridge.Unknown

        Evergreen.V19.Bridge.UserOnDevice p0 ->
            Evergreen.V20.Bridge.UserOnDevice (p0 |> migrate_Bridge_UserOnDeviceData)


migrate_Bridge_UserOnDeviceData : Evergreen.V19.Bridge.UserOnDeviceData -> Evergreen.V20.Bridge.UserOnDeviceData
migrate_Bridge_UserOnDeviceData old =
    old |> migrate_UserManagement_UserOnDeviceData


migrate_Components_Toast_Model : Evergreen.V19.Components.Toast.Model -> Evergreen.V20.Components.Toast.Model
migrate_Components_Toast_Model old =
    { toasts = old.toasts |> Dict.map (\k -> migrate_Components_Toast_Toast)
    , nextId = old.nextId
    }


migrate_Components_Toast_Msg : Evergreen.V19.Components.Toast.Msg -> Evergreen.V20.Components.Toast.Msg
migrate_Components_Toast_Msg old =
    case old of
        Evergreen.V19.Components.Toast.RemoveToast p0 ->
            Evergreen.V20.Components.Toast.RemoveToast p0


migrate_Components_Toast_Position : Evergreen.V19.Components.Toast.Position -> Evergreen.V20.Components.Toast.Position
migrate_Components_Toast_Position old =
    case old of
        Evergreen.V19.Components.Toast.TopRight ->
            Evergreen.V20.Components.Toast.TopRight

        Evergreen.V19.Components.Toast.TopLeft ->
            Evergreen.V20.Components.Toast.TopLeft

        Evergreen.V19.Components.Toast.BottomRight ->
            Evergreen.V20.Components.Toast.BottomRight

        Evergreen.V19.Components.Toast.BottomLeft ->
            Evergreen.V20.Components.Toast.BottomLeft


migrate_Components_Toast_Toast : Evergreen.V19.Components.Toast.Toast -> Evergreen.V20.Components.Toast.Toast
migrate_Components_Toast_Toast old =
    { id = old.id
    , message = old.message
    , toastType = old.toastType |> migrate_Components_Toast_ToastType
    , position = old.position |> migrate_Components_Toast_Position
    , duration = old.duration
    , withRemove = old.withRemove
    }


migrate_Components_Toast_ToastType : Evergreen.V19.Components.Toast.ToastType -> Evergreen.V20.Components.Toast.ToastType
migrate_Components_Toast_ToastType old =
    case old of
        Evergreen.V19.Components.Toast.Success ->
            Evergreen.V20.Components.Toast.Success

        Evergreen.V19.Components.Toast.Error ->
            Evergreen.V20.Components.Toast.Error

        Evergreen.V19.Components.Toast.Info ->
            Evergreen.V20.Components.Toast.Info

        Evergreen.V19.Components.Toast.Warning ->
            Evergreen.V20.Components.Toast.Warning


migrate_Event_EventData : Evergreen.V19.Event.EventData -> Evergreen.V20.Event.EventData
migrate_Event_EventData old =
    case old of
        Evergreen.V19.Event.ListCreated p0 ->
            Evergreen.V20.Event.ListCreated (p0 |> migrate_Event_ListCreatedData)

        Evergreen.V19.Event.ListUpdated p0 ->
            Evergreen.V20.Event.ListUpdated (p0 |> migrate_Event_ListUpdatedData)

        Evergreen.V19.Event.ListSharedWithUser p0 ->
            Evergreen.V20.Event.ListSharedWithUser (p0 |> migrate_Event_ListSharedWithUserData)

        Evergreen.V19.Event.ItemCreated p0 ->
            Evergreen.V20.Event.ItemCreated (p0 |> migrate_Event_ItemCreatedData)

        Evergreen.V19.Event.ItemStateChanged p0 ->
            Evergreen.V20.Event.ItemStateChanged (p0 |> migrate_Event_ItemStateChangedData)

        Evergreen.V19.Event.ItemUpdated p0 ->
            Evergreen.V20.Event.ItemUpdated (p0 |> migrate_Event_ItemUpdatedData)


migrate_Event_EventDefinition : Evergreen.V19.Event.EventDefinition -> Evergreen.V20.Event.EventDefinition
migrate_Event_EventDefinition old =
    case old of
        Evergreen.V19.Event.Event p0 p1 ->
            Evergreen.V20.Event.Event (p0 |> migrate_Event_EventMetadata)
                (p1 |> migrate_Event_EventData)


migrate_Event_EventMetadata : Evergreen.V19.Event.EventMetadata -> Evergreen.V20.Event.EventMetadata
migrate_Event_EventMetadata old =
    old


migrate_Event_ItemCreatedData : Evergreen.V19.Event.ItemCreatedData -> Evergreen.V20.Event.ItemCreatedData
migrate_Event_ItemCreatedData old =
    { itemId = old.itemId
    , itemName = old.itemName
    , itemDescription = old.itemDescription
    , itemPriority = old.itemPriority |> Maybe.map migrate_ItemPriority_ItemPriority
    }


migrate_Event_ItemStateChangedData : Evergreen.V19.Event.ItemStateChangedData -> Evergreen.V20.Event.ItemStateChangedData
migrate_Event_ItemStateChangedData old =
    old


migrate_Event_ItemUpdatedData : Evergreen.V19.Event.ItemUpdatedData -> Evergreen.V20.Event.ItemUpdatedData
migrate_Event_ItemUpdatedData old =
    { itemId = old.itemId
    , listId = old.listId
    , name = old.name
    , completed = old.completed
    , itemPriority = old.itemPriority |> Maybe.map migrate_ItemPriority_ItemPriority
    , description = old.description
    }


migrate_Event_ListCreatedData : Evergreen.V19.Event.ListCreatedData -> Evergreen.V20.Event.ListCreatedData
migrate_Event_ListCreatedData old =
    old


migrate_Event_ListSharedWithUserData : Evergreen.V19.Event.ListSharedWithUserData -> Evergreen.V20.Event.ListSharedWithUserData
migrate_Event_ListSharedWithUserData old =
    old


migrate_Event_ListUpdatedData : Evergreen.V19.Event.ListUpdatedData -> Evergreen.V20.Event.ListUpdatedData
migrate_Event_ListUpdatedData old =
    old


migrate_Event_PinkItem : Evergreen.V19.Event.PinkItem -> Evergreen.V20.Event.PinkItem
migrate_Event_PinkItem old =
    { name = old.name
    , itemId = old.itemId
    , description = old.description
    , createdAt = old.createdAt
    , completedAt = old.completedAt
    , lastUpdatedAt = old.lastUpdatedAt
    , numberOfUpdates = old.numberOfUpdates
    , priority = old.priority |> migrate_ItemPriority_ItemPriority
    }


migrate_Event_PinkList : Evergreen.V19.Event.PinkList -> Evergreen.V20.Event.PinkList
migrate_Event_PinkList old =
    { name = old.name
    , listId = old.listId
    , items = old.items |> Dict.map (\k -> migrate_Event_PinkItem)
    , createdAt = old.createdAt
    , lastUpdatedAt = old.lastUpdatedAt
    , numberOfUpdates = old.numberOfUpdates
    , users = old.users
    }


migrate_Event_State : Evergreen.V19.Event.State -> Evergreen.V20.Event.State
migrate_Event_State old =
    { lists = old.lists |> Dict.map (\k -> migrate_Event_PinkList)
    }


migrate_ItemPriority_ItemPriority : Evergreen.V19.ItemPriority.ItemPriority -> Evergreen.V20.ItemPriority.ItemPriority
migrate_ItemPriority_ItemPriority old =
    case old of
        Evergreen.V19.ItemPriority.LowItemPriority ->
            Evergreen.V20.ItemPriority.LowItemPriority

        Evergreen.V19.ItemPriority.MediumItemPriority ->
            Evergreen.V20.ItemPriority.MediumItemPriority

        Evergreen.V19.ItemPriority.HighItemPriority ->
            Evergreen.V20.ItemPriority.HighItemPriority

        Evergreen.V19.ItemPriority.HighestItemPriority ->
            Evergreen.V20.ItemPriority.HighestItemPriority


migrate_Layouts_Scaffold_Model : Evergreen.V19.Layouts.Scaffold.Model -> Evergreen.V20.Layouts.Scaffold.Model
migrate_Layouts_Scaffold_Model old =
    { user = old.user |> migrate_Auth_User
    }


migrate_Layouts_Scaffold_Msg : Evergreen.V19.Layouts.Scaffold.Msg -> Evergreen.V20.Layouts.Scaffold.Msg
migrate_Layouts_Scaffold_Msg old =
    case old of
        Evergreen.V19.Layouts.Scaffold.CloseSidebarClicked ->
            Evergreen.V20.Layouts.Scaffold.CloseSidebarClicked

        Evergreen.V19.Layouts.Scaffold.OpenSidebarClicked ->
            Evergreen.V20.Layouts.Scaffold.OpenSidebarClicked

        Evergreen.V19.Layouts.Scaffold.NavigationClicked p0 ->
            Evergreen.V20.Layouts.Scaffold.NavigationClicked (p0 |> migrate_Route_Path_Path)

        Evergreen.V19.Layouts.Scaffold.ToastRemoveToast p0 ->
            Evergreen.V20.Layouts.Scaffold.ToastRemoveToast p0


migrate_Main_Layouts_Model_Model : Evergreen.V19.Main.Layouts.Model.Model -> Evergreen.V20.Main.Layouts.Model.Model
migrate_Main_Layouts_Model_Model old =
    case old of
        Evergreen.V19.Main.Layouts.Model.Scaffold p0 ->
            Evergreen.V20.Main.Layouts.Model.Scaffold
                { scaffold = p0.scaffold |> migrate_Layouts_Scaffold_Model
                }


migrate_Main_Layouts_Msg_Msg : Evergreen.V19.Main.Layouts.Msg.Msg -> Evergreen.V20.Main.Layouts.Msg.Msg
migrate_Main_Layouts_Msg_Msg old =
    case old of
        Evergreen.V19.Main.Layouts.Msg.Scaffold p0 ->
            Evergreen.V20.Main.Layouts.Msg.Scaffold (p0 |> migrate_Layouts_Scaffold_Msg)


migrate_Main_Model : Evergreen.V19.Main.Model -> Evergreen.V20.Main.Model
migrate_Main_Model old =
    { key = old.key
    , url = old.url
    , page = old.page |> migrate_Main_Pages_Model_Model
    , layout = old.layout |> Maybe.map migrate_Main_Layouts_Model_Model
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Main_Msg : Evergreen.V19.Main.Msg -> Evergreen.V20.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V19.Main.UrlRequested p0 ->
            Evergreen.V20.Main.UrlRequested p0

        Evergreen.V19.Main.UrlChanged p0 ->
            Evergreen.V20.Main.UrlChanged p0

        Evergreen.V19.Main.Page p0 ->
            Evergreen.V20.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V19.Main.Layout p0 ->
            Evergreen.V20.Main.Layout (p0 |> migrate_Main_Layouts_Msg_Msg)

        Evergreen.V19.Main.Shared p0 ->
            Evergreen.V20.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V19.Main.Batch p0 ->
            Evergreen.V20.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Model_Model : Evergreen.V19.Main.Pages.Model.Model -> Evergreen.V20.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V19.Main.Pages.Model.Home_ p0 ->
            Evergreen.V20.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V19.Main.Pages.Model.Account p0 ->
            Evergreen.V20.Main.Pages.Model.Account (p0 |> migrate_Pages_Account_Model)

        Evergreen.V19.Main.Pages.Model.Admin p0 ->
            Evergreen.V20.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V19.Main.Pages.Model.Credits p0 ->
            Evergreen.V20.Main.Pages.Model.Credits (p0 |> migrate_Pages_Credits_Model)

        Evergreen.V19.Main.Pages.Model.List_ImportShared p0 ->
            Evergreen.V20.Main.Pages.Model.List_ImportShared (p0 |> migrate_Pages_List_ImportShared_Model)

        Evergreen.V19.Main.Pages.Model.Lists p0 ->
            Evergreen.V20.Main.Pages.Model.Lists (p0 |> migrate_Pages_Lists_Model)

        Evergreen.V19.Main.Pages.Model.Lists_Create p0 ->
            Evergreen.V20.Main.Pages.Model.Lists_Create (p0 |> migrate_Pages_Lists_Create_Model)

        Evergreen.V19.Main.Pages.Model.Lists_Edit_ListId_ p0 p1 ->
            Evergreen.V20.Main.Pages.Model.Lists_Edit_ListId_ p0 (p1 |> migrate_Pages_Lists_Edit_ListId__Model)

        Evergreen.V19.Main.Pages.Model.Lists_Id__CreateItem p0 p1 ->
            Evergreen.V20.Main.Pages.Model.Lists_Id__CreateItem p0
                (p1 |> migrate_Pages_Lists_Id__CreateItem_Model)

        Evergreen.V19.Main.Pages.Model.Lists_ListId_ p0 p1 ->
            Evergreen.V20.Main.Pages.Model.Lists_ListId_ p0 (p1 |> migrate_Pages_Lists_ListId__Model)

        Evergreen.V19.Main.Pages.Model.Lists_ListId__Edit_ItemId_ p0 p1 ->
            Evergreen.V20.Main.Pages.Model.Lists_ListId__Edit_ItemId_ p0
                (p1 |> migrate_Pages_Lists_ListId__Edit_ItemId__Model)

        Evergreen.V19.Main.Pages.Model.Manual p0 ->
            Evergreen.V20.Main.Pages.Model.Admin_Manual p0

        Evergreen.V19.Main.Pages.Model.Settings p0 ->
            Evergreen.V20.Main.Pages.Model.Settings (p0 |> migrate_Pages_Settings_Model)

        Evergreen.V19.Main.Pages.Model.Setup p0 ->
            Evergreen.V20.Main.Pages.Model.Setup (p0 |> migrate_Pages_Setup_Model)

        Evergreen.V19.Main.Pages.Model.Setup_Connect p0 ->
            Evergreen.V20.Main.Pages.Model.Setup_Connect (p0 |> migrate_Pages_Setup_Connect_Model)

        Evergreen.V19.Main.Pages.Model.Setup_NewAccount p0 ->
            Evergreen.V20.Main.Pages.Model.Setup_NewAccount (p0 |> migrate_Pages_Setup_NewAccount_Model)

        Evergreen.V19.Main.Pages.Model.SetupKnown p0 ->
            Evergreen.V20.Main.Pages.Model.SetupKnown (p0 |> migrate_Pages_SetupKnown_Model)

        Evergreen.V19.Main.Pages.Model.Share_ListId_ p0 p1 ->
            Evergreen.V20.Main.Pages.Model.Share_ListId_ p0 (p1 |> migrate_Pages_Share_ListId__Model)

        Evergreen.V19.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V20.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V19.Main.Pages.Model.Redirecting_ ->
            Evergreen.V20.Main.Pages.Model.Redirecting_

        Evergreen.V19.Main.Pages.Model.Loading_ ->
            Evergreen.V20.Main.Pages.Model.Loading_


migrate_Main_Pages_Msg_Msg : Evergreen.V19.Main.Pages.Msg.Msg -> Evergreen.V20.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V19.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V20.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V19.Main.Pages.Msg.Account p0 ->
            Evergreen.V20.Main.Pages.Msg.Account (p0 |> migrate_Pages_Account_Msg)

        Evergreen.V19.Main.Pages.Msg.Admin _ ->
            Evergreen.V20.Main.Pages.Msg.Admin_Menu Evergreen.V20.Pages.Admin.Menu.NoOp

        Evergreen.V19.Main.Pages.Msg.Credits p0 ->
            Evergreen.V20.Main.Pages.Msg.Credits (p0 |> migrate_Pages_Credits_Msg)

        Evergreen.V19.Main.Pages.Msg.List_ImportShared p0 ->
            Evergreen.V20.Main.Pages.Msg.List_ImportShared (p0 |> migrate_Pages_List_ImportShared_Msg)

        Evergreen.V19.Main.Pages.Msg.Lists p0 ->
            Evergreen.V20.Main.Pages.Msg.Lists (p0 |> migrate_Pages_Lists_Msg)

        Evergreen.V19.Main.Pages.Msg.Lists_Create p0 ->
            Evergreen.V20.Main.Pages.Msg.Lists_Create (p0 |> migrate_Pages_Lists_Create_Msg)

        Evergreen.V19.Main.Pages.Msg.Lists_Edit_ListId_ p0 ->
            Evergreen.V20.Main.Pages.Msg.Lists_Edit_ListId_ (p0 |> migrate_Pages_Lists_Edit_ListId__Msg)

        Evergreen.V19.Main.Pages.Msg.Lists_Id__CreateItem p0 ->
            Evergreen.V20.Main.Pages.Msg.Lists_Id__CreateItem (p0 |> migrate_Pages_Lists_Id__CreateItem_Msg)

        Evergreen.V19.Main.Pages.Msg.Lists_ListId_ p0 ->
            Evergreen.V20.Main.Pages.Msg.Lists_ListId_ (p0 |> migrate_Pages_Lists_ListId__Msg)

        Evergreen.V19.Main.Pages.Msg.Lists_ListId__Edit_ItemId_ p0 ->
            Evergreen.V20.Main.Pages.Msg.Lists_ListId__Edit_ItemId_ (p0 |> migrate_Pages_Lists_ListId__Edit_ItemId__Msg)

        Evergreen.V19.Main.Pages.Msg.Settings p0 ->
            Evergreen.V20.Main.Pages.Msg.Settings (p0 |> migrate_Pages_Settings_Msg)

        Evergreen.V19.Main.Pages.Msg.Setup p0 ->
            Evergreen.V20.Main.Pages.Msg.Setup (p0 |> migrate_Pages_Setup_Msg)

        Evergreen.V19.Main.Pages.Msg.Setup_Connect p0 ->
            Evergreen.V20.Main.Pages.Msg.Setup_Connect (p0 |> migrate_Pages_Setup_Connect_Msg)

        Evergreen.V19.Main.Pages.Msg.Setup_NewAccount p0 ->
            Evergreen.V20.Main.Pages.Msg.Setup_NewAccount (p0 |> migrate_Pages_Setup_NewAccount_Msg)

        Evergreen.V19.Main.Pages.Msg.SetupKnown p0 ->
            Evergreen.V20.Main.Pages.Msg.SetupKnown (p0 |> migrate_Pages_SetupKnown_Msg)

        Evergreen.V19.Main.Pages.Msg.Share_ListId_ p0 ->
            Evergreen.V20.Main.Pages.Msg.Share_ListId_ (p0 |> migrate_Pages_Share_ListId__Msg)

        Evergreen.V19.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V20.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)

        Evergreen.V19.Main.Pages.Msg.Manual p0 ->
            Evergreen.V20.Main.Pages.Msg.Admin_Manual (p0 |> migrate_Pages_Admin_Manual_Msg)


migrate_Pages_Admin_Manual_Msg : Evergreen.V19.Pages.Manual.Msg -> Evergreen.V20.Pages.Admin.Manual.Msg
migrate_Pages_Admin_Manual_Msg old =
    case old of
        Evergreen.V19.Pages.Manual.AdminDataRequested ->
            Evergreen.V20.Pages.Admin.Manual.CreateUserButtonClicked

        Evergreen.V19.Pages.Manual.CreateUserButtonClicked ->
            Evergreen.V20.Pages.Admin.Manual.CreateUserButtonClicked

        Evergreen.V19.Pages.Manual.NewDeviceIdChanged p0 ->
            Evergreen.V20.Pages.Admin.Manual.NewDeviceIdChanged p0

        Evergreen.V19.Pages.Manual.NewDeviceNameChanged p0 ->
            Evergreen.V20.Pages.Admin.Manual.NewDeviceNameChanged p0

        Evergreen.V19.Pages.Manual.NewUseridChanged p0 ->
            Evergreen.V20.Pages.Admin.Manual.NewUseridChanged p0

        Evergreen.V19.Pages.Manual.NewUserNameChanged p0 ->
            Evergreen.V20.Pages.Admin.Manual.NewUserNameChanged p0

        Evergreen.V19.Pages.Manual.ReconnectUser ->
            Evergreen.V20.Pages.Admin.Manual.ReconnectUser


migrate_Pages_Account_Model : Evergreen.V19.Pages.Account.Model -> Evergreen.V20.Pages.Account.Model
migrate_Pages_Account_Model old =
    old


migrate_Pages_Account_Msg : Evergreen.V19.Pages.Account.Msg -> Evergreen.V20.Pages.Account.Msg
migrate_Pages_Account_Msg old =
    case old of
        Evergreen.V19.Pages.Account.NoOp ->
            Evergreen.V20.Pages.Account.NoOp

        Evergreen.V19.Pages.Account.LogoutClicked ->
            Evergreen.V20.Pages.Account.LogoutClicked

        Evergreen.V19.Pages.Account.ConnectDeviceClicked ->
            Evergreen.V20.Pages.Account.ConnectDeviceClicked


migrate_Pages_Credits_Model : Evergreen.V19.Pages.Credits.Model -> Evergreen.V20.Pages.Credits.Model
migrate_Pages_Credits_Model old =
    old


migrate_Pages_Credits_Msg : Evergreen.V19.Pages.Credits.Msg -> Evergreen.V20.Pages.Credits.Msg
migrate_Pages_Credits_Msg old =
    case old of
        Evergreen.V19.Pages.Credits.NoOp ->
            Evergreen.V20.Pages.Credits.NoOp


migrate_Pages_Home__Model : Evergreen.V19.Pages.Home_.Model -> Evergreen.V20.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V19.Pages.Home_.Msg -> Evergreen.V20.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V19.Pages.Home_.LogoutClicked ->
            Evergreen.V20.Pages.Home_.LogoutClicked


migrate_Pages_List_ImportShared_Model : Evergreen.V19.Pages.List.ImportShared.Model -> Evergreen.V20.Pages.List.ImportShared.Model
migrate_Pages_List_ImportShared_Model old =
    old


migrate_Pages_List_ImportShared_Msg : Evergreen.V19.Pages.List.ImportShared.Msg -> Evergreen.V20.Pages.List.ImportShared.Msg
migrate_Pages_List_ImportShared_Msg old =
    case old of
        Evergreen.V19.Pages.List.ImportShared.InputChanged p0 ->
            Evergreen.V20.Pages.List.ImportShared.InputChanged p0

        Evergreen.V19.Pages.List.ImportShared.ImportClicked ->
            Evergreen.V20.Pages.List.ImportShared.ImportClicked


migrate_Pages_Lists_Create_Model : Evergreen.V19.Pages.Lists.Create.Model -> Evergreen.V20.Pages.Lists.Create.Model
migrate_Pages_Lists_Create_Model old =
    old


migrate_Pages_Lists_Create_Msg : Evergreen.V19.Pages.Lists.Create.Msg -> Evergreen.V20.Pages.Lists.Create.Msg
migrate_Pages_Lists_Create_Msg old =
    case old of
        Evergreen.V19.Pages.Lists.Create.ListNameChanged p0 ->
            Evergreen.V20.Pages.Lists.Create.ListNameChanged p0

        Evergreen.V19.Pages.Lists.Create.CreateListButtonClicked ->
            Evergreen.V20.Pages.Lists.Create.CreateListButtonClicked

        Evergreen.V19.Pages.Lists.Create.GotTimeForCreateList p0 ->
            Evergreen.V20.Pages.Lists.Create.GotTimeForCreateList p0


migrate_Pages_Lists_Edit_ListId__Model : Evergreen.V19.Pages.Lists.Edit.ListId_.Model -> Evergreen.V20.Pages.Lists.Edit.ListId_.Model
migrate_Pages_Lists_Edit_ListId__Model old =
    old


migrate_Pages_Lists_Edit_ListId__Msg : Evergreen.V19.Pages.Lists.Edit.ListId_.Msg -> Evergreen.V20.Pages.Lists.Edit.ListId_.Msg
migrate_Pages_Lists_Edit_ListId__Msg old =
    case old of
        Evergreen.V19.Pages.Lists.Edit.ListId_.ListNameChanged p0 ->
            Evergreen.V20.Pages.Lists.Edit.ListId_.ListNameChanged p0

        Evergreen.V19.Pages.Lists.Edit.ListId_.UpdateListButtonClicked ->
            Evergreen.V20.Pages.Lists.Edit.ListId_.UpdateListButtonClicked

        Evergreen.V19.Pages.Lists.Edit.ListId_.GotTimeForUpdateList p0 ->
            Evergreen.V20.Pages.Lists.Edit.ListId_.GotTimeForUpdateList p0

        Evergreen.V19.Pages.Lists.Edit.ListId_.CopyShareLinkClicked p0 ->
            Evergreen.V20.Pages.Lists.Edit.ListId_.CopyShareLinkClicked p0


migrate_Pages_Lists_Id__CreateItem_Model : Evergreen.V19.Pages.Lists.Id_.CreateItem.Model -> Evergreen.V20.Pages.Lists.Id_.CreateItem.Model
migrate_Pages_Lists_Id__CreateItem_Model old =
    { listId = old.listId
    , itemName = old.itemName
    , itemDescription = old.itemDescription
    , itemPriority = old.itemPriority |> migrate_ItemPriority_ItemPriority
    , error = old.error
    }


migrate_Pages_Lists_Id__CreateItem_Msg : Evergreen.V19.Pages.Lists.Id_.CreateItem.Msg -> Evergreen.V20.Pages.Lists.Id_.CreateItem.Msg
migrate_Pages_Lists_Id__CreateItem_Msg old =
    case old of
        Evergreen.V19.Pages.Lists.Id_.CreateItem.ItemNameChanged p0 ->
            Evergreen.V20.Pages.Lists.Id_.CreateItem.ItemNameChanged p0

        Evergreen.V19.Pages.Lists.Id_.CreateItem.ItemDescriptionChanged p0 ->
            Evergreen.V20.Pages.Lists.Id_.CreateItem.ItemDescriptionChanged p0

        Evergreen.V19.Pages.Lists.Id_.CreateItem.CreateItemButtonClicked ->
            Evergreen.V20.Pages.Lists.Id_.CreateItem.CreateItemButtonClicked

        Evergreen.V19.Pages.Lists.Id_.CreateItem.GotTimeForCreateItem p0 ->
            Evergreen.V20.Pages.Lists.Id_.CreateItem.GotTimeForCreateItem p0

        Evergreen.V19.Pages.Lists.Id_.CreateItem.ItemPriorityChanged p0 ->
            Evergreen.V20.Pages.Lists.Id_.CreateItem.ItemPriorityChanged p0


migrate_Pages_Lists_ListId__Edit_ItemId__Model : Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.Model -> Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.Model
migrate_Pages_Lists_ListId__Edit_ItemId__Model old =
    { itemName = old.itemName
    , initialItemName = old.initialItemName
    , itemChecked = old.itemChecked
    , initialItemChecked = old.initialItemChecked
    , itemPriority = old.itemPriority |> migrate_ItemPriority_ItemPriority
    , initialItemPriority = old.initialItemPriority |> migrate_ItemPriority_ItemPriority
    , itemDescription = old.itemDescription
    , initialItemDescription = old.initialItemDescription
    , listId = old.listId
    , itemId = old.itemId
    , createdAt = old.createdAt
    , lastUpdatedAt = old.lastUpdatedAt
    , numberOfUpdates = old.numberOfUpdates
    }


migrate_Pages_Lists_ListId__Edit_ItemId__Msg : Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.Msg -> Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.Msg
migrate_Pages_Lists_ListId__Edit_ItemId__Msg old =
    case old of
        Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.SaveClicked ->
            Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.SaveClicked

        Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.NameChanged p0 ->
            Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.NameChanged p0

        Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.DoneClicked p0 ->
            Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.DoneClicked p0

        Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.GotTimeForUpdatedItem p0 ->
            Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.GotTimeForUpdatedItem p0

        Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.ItemPriorityChanged p0 ->
            Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.ItemPriorityChanged p0

        Evergreen.V19.Pages.Lists.ListId_.Edit.ItemId_.ItemDescriptionChanged p0 ->
            Evergreen.V20.Pages.Lists.ListId_.Edit.ItemId_.ItemDescriptionChanged p0


migrate_Pages_Lists_ListId__Model : Evergreen.V19.Pages.Lists.ListId_.Model -> Evergreen.V20.Pages.Lists.ListId_.Model
migrate_Pages_Lists_ListId__Model old =
    old


migrate_Pages_Lists_ListId__Msg : Evergreen.V19.Pages.Lists.ListId_.Msg -> Evergreen.V20.Pages.Lists.ListId_.Msg
migrate_Pages_Lists_ListId__Msg old =
    case old of
        Evergreen.V19.Pages.Lists.ListId_.ItemCheckedToggled p0 p1 ->
            Evergreen.V20.Pages.Lists.ListId_.ItemCheckedToggled p0 p1

        Evergreen.V19.Pages.Lists.ListId_.GotTimeForItemCheckedToggled p0 p1 p2 ->
            Evergreen.V20.Pages.Lists.ListId_.GotTimeForItemCheckedToggled p0 p1 p2

        Evergreen.V19.Pages.Lists.ListId_.AddItemClicked ->
            Evergreen.V20.Pages.Lists.ListId_.AddItemClicked

        Evergreen.V19.Pages.Lists.ListId_.GotCurrentTime p0 ->
            Evergreen.V20.Pages.Lists.ListId_.GotCurrentTime p0

        Evergreen.V19.Pages.Lists.ListId_.ToggleArchiveClicked ->
            Evergreen.V20.Pages.Lists.ListId_.ToggleArchiveClicked


migrate_Pages_Lists_Model : Evergreen.V19.Pages.Lists.Model -> Evergreen.V20.Pages.Lists.Model
migrate_Pages_Lists_Model old =
    old


migrate_Pages_Lists_Msg : Evergreen.V19.Pages.Lists.Msg -> Evergreen.V20.Pages.Lists.Msg
migrate_Pages_Lists_Msg old =
    case old of
        Evergreen.V19.Pages.Lists.CreateDummyList ->
            Evergreen.V20.Pages.Lists.CreateDummyList

        Evergreen.V19.Pages.Lists.CreatNewListClicked ->
            Evergreen.V20.Pages.Lists.CreatNewListClicked

        Evergreen.V19.Pages.Lists.ImportSharedListClicked ->
            Evergreen.V20.Pages.Lists.ImportSharedListClicked


migrate_Pages_NotFound__Model : Evergreen.V19.Pages.NotFound_.Model -> Evergreen.V20.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_NotFound__Msg : Evergreen.V19.Pages.NotFound_.Msg -> Evergreen.V20.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V19.Pages.NotFound_.NoOp ->
            Evergreen.V20.Pages.NotFound_.NoOp


migrate_Pages_Settings_Model : Evergreen.V19.Pages.Settings.Model -> Evergreen.V20.Pages.Settings.Model
migrate_Pages_Settings_Model old =
    old


migrate_Pages_Settings_Msg : Evergreen.V19.Pages.Settings.Msg -> Evergreen.V20.Pages.Settings.Msg
migrate_Pages_Settings_Msg old =
    case old of
        Evergreen.V19.Pages.Settings.NoOp ->
            Evergreen.V20.Pages.Settings.NoOp


migrate_Pages_SetupKnown_Model : Evergreen.V19.Pages.SetupKnown.Model -> Evergreen.V20.Pages.SetupKnown.Model
migrate_Pages_SetupKnown_Model old =
    old


migrate_Pages_SetupKnown_Msg : Evergreen.V19.Pages.SetupKnown.Msg -> Evergreen.V20.Pages.SetupKnown.Msg
migrate_Pages_SetupKnown_Msg old =
    case old of
        Evergreen.V19.Pages.SetupKnown.NoOp ->
            Evergreen.V20.Pages.SetupKnown.NoOp


migrate_Pages_Setup_Connect_Model : Evergreen.V19.Pages.Setup.Connect.Model -> Evergreen.V20.Pages.Setup.Connect.Model
migrate_Pages_Setup_Connect_Model old =
    old


migrate_Pages_Setup_Connect_Msg : Evergreen.V19.Pages.Setup.Connect.Msg -> Evergreen.V20.Pages.Setup.Connect.Msg
migrate_Pages_Setup_Connect_Msg old =
    case old of
        Evergreen.V19.Pages.Setup.Connect.CodeInputChanged p0 ->
            Evergreen.V20.Pages.Setup.Connect.CodeInputChanged p0

        Evergreen.V19.Pages.Setup.Connect.DeviceNameChanged p0 ->
            Evergreen.V20.Pages.Setup.Connect.DeviceNameChanged p0

        Evergreen.V19.Pages.Setup.Connect.OkButtonClicked ->
            Evergreen.V20.Pages.Setup.Connect.OkButtonClicked


migrate_Pages_Setup_Model : Evergreen.V19.Pages.Setup.Model -> Evergreen.V20.Pages.Setup.Model
migrate_Pages_Setup_Model old =
    { redirect = old.redirect
    , initialUserdata = old.initialUserdata |> Maybe.map migrate_Bridge_User
    }


migrate_Pages_Setup_Msg : Evergreen.V19.Pages.Setup.Msg -> Evergreen.V20.Pages.Setup.Msg
migrate_Pages_Setup_Msg old =
    case old of
        Evergreen.V19.Pages.Setup.CreateNewAccount ->
            Evergreen.V20.Pages.Setup.CreateNewAccount

        Evergreen.V19.Pages.Setup.ConnectExistingAccount ->
            Evergreen.V20.Pages.Setup.ConnectExistingAccount

        Evergreen.V19.Pages.Setup.Logout ->
            Evergreen.V20.Pages.Setup.Logout

        Evergreen.V19.Pages.Setup.ShowNewConnectionInfo ->
            Evergreen.V20.Pages.Setup.ShowNewConnectionInfo

        Evergreen.V19.Pages.Setup.GotTime p0 ->
            Evergreen.V20.Pages.Setup.GotTime p0

        Evergreen.V19.Pages.Setup.NoOp ->
            Evergreen.V20.Pages.Setup.NoOp


migrate_Pages_Setup_NewAccount_Model : Evergreen.V19.Pages.Setup.NewAccount.Model -> Evergreen.V20.Pages.Setup.NewAccount.Model
migrate_Pages_Setup_NewAccount_Model old =
    old


migrate_Pages_Setup_NewAccount_Msg : Evergreen.V19.Pages.Setup.NewAccount.Msg -> Evergreen.V20.Pages.Setup.NewAccount.Msg
migrate_Pages_Setup_NewAccount_Msg old =
    case old of
        Evergreen.V19.Pages.Setup.NewAccount.Create ->
            Evergreen.V20.Pages.Setup.NewAccount.Create

        Evergreen.V19.Pages.Setup.NewAccount.UsernameChanged p0 ->
            Evergreen.V20.Pages.Setup.NewAccount.UsernameChanged p0

        Evergreen.V19.Pages.Setup.NewAccount.DeviceNameChanged p0 ->
            Evergreen.V20.Pages.Setup.NewAccount.DeviceNameChanged p0


migrate_Pages_Share_ListId__Model : Evergreen.V19.Pages.Share.ListId_.Model -> Evergreen.V20.Pages.Share.ListId_.Model
migrate_Pages_Share_ListId__Model old =
    { listId = old.listId
    , state = old.state |> migrate_Pages_Share_ListId__States
    }


migrate_Pages_Share_ListId__Msg : Evergreen.V19.Pages.Share.ListId_.Msg -> Evergreen.V20.Pages.Share.ListId_.Msg
migrate_Pages_Share_ListId__Msg old =
    case old of
        Evergreen.V19.Pages.Share.ListId_.GotListSubscriptionAdded p0 ->
            Evergreen.V20.Pages.Share.ListId_.GotListSubscriptionAdded p0

        Evergreen.V19.Pages.Share.ListId_.GotListSubscriptionFailed ->
            Evergreen.V20.Pages.Share.ListId_.GotListSubscriptionFailed

        Evergreen.V19.Pages.Share.ListId_.TimeoutSubscriptionWait ->
            Evergreen.V20.Pages.Share.ListId_.TimeoutSubscriptionWait

        Evergreen.V19.Pages.Share.ListId_.GoBackClicked ->
            Evergreen.V20.Pages.Share.ListId_.GoBackClicked


migrate_Pages_Share_ListId__States : Evergreen.V19.Pages.Share.ListId_.States -> Evergreen.V20.Pages.Share.ListId_.States
migrate_Pages_Share_ListId__States old =
    case old of
        Evergreen.V19.Pages.Share.ListId_.InitializingSync ->
            Evergreen.V20.Pages.Share.ListId_.InitializingSync

        Evergreen.V19.Pages.Share.ListId_.Syncing ->
            Evergreen.V20.Pages.Share.ListId_.Syncing

        Evergreen.V19.Pages.Share.ListId_.DoneSyncing ->
            Evergreen.V20.Pages.Share.ListId_.DoneSyncing

        Evergreen.V19.Pages.Share.ListId_.ErrorSyncing p0 ->
            Evergreen.V20.Pages.Share.ListId_.ErrorSyncing p0


migrate_Role_Role : Evergreen.V19.Role.Role -> Evergreen.V20.Role.Role
migrate_Role_Role old =
    case old of
        Evergreen.V19.Role.User ->
            Evergreen.V20.Role.User

        Evergreen.V19.Role.Admin ->
            Evergreen.V20.Role.Admin


migrate_Route_Path_Path : Evergreen.V19.Route.Path.Path -> Evergreen.V20.Route.Path.Path
migrate_Route_Path_Path old =
    case old of
        Evergreen.V19.Route.Path.Home_ ->
            Evergreen.V20.Route.Path.Home_

        Evergreen.V19.Route.Path.Account ->
            Evergreen.V20.Route.Path.Account

        Evergreen.V19.Route.Path.Admin ->
            Evergreen.V20.Route.Path.Admin_Menu

        Evergreen.V19.Route.Path.Credits ->
            Evergreen.V20.Route.Path.Credits

        Evergreen.V19.Route.Path.List_ImportShared ->
            Evergreen.V20.Route.Path.List_ImportShared

        Evergreen.V19.Route.Path.Lists ->
            Evergreen.V20.Route.Path.Lists

        Evergreen.V19.Route.Path.Lists_Create ->
            Evergreen.V20.Route.Path.Lists_Create

        Evergreen.V19.Route.Path.Lists_Edit_ListId_ p0 ->
            Evergreen.V20.Route.Path.Lists_Edit_ListId_ p0

        Evergreen.V19.Route.Path.Lists_Id__CreateItem p0 ->
            Evergreen.V20.Route.Path.Lists_Id__CreateItem p0

        Evergreen.V19.Route.Path.Lists_ListId_ p0 ->
            Evergreen.V20.Route.Path.Lists_ListId_ p0

        Evergreen.V19.Route.Path.Lists_ListId__Edit_ItemId_ p0 ->
            Evergreen.V20.Route.Path.Lists_ListId__Edit_ItemId_ p0

        Evergreen.V19.Route.Path.Manual ->
            Evergreen.V20.Route.Path.Admin_Manual

        Evergreen.V19.Route.Path.Settings ->
            Evergreen.V20.Route.Path.Settings

        Evergreen.V19.Route.Path.Setup ->
            Evergreen.V20.Route.Path.Setup

        Evergreen.V19.Route.Path.Setup_Connect ->
            Evergreen.V20.Route.Path.Setup_Connect

        Evergreen.V19.Route.Path.Setup_NewAccount ->
            Evergreen.V20.Route.Path.Setup_NewAccount

        Evergreen.V19.Route.Path.SetupKnown ->
            Evergreen.V20.Route.Path.SetupKnown

        Evergreen.V19.Route.Path.Share_ListId_ p0 ->
            Evergreen.V20.Route.Path.Share_ListId_ p0

        Evergreen.V19.Route.Path.NotFound_ ->
            Evergreen.V20.Route.Path.NotFound_


migrate_Shared_Model : Evergreen.V19.Shared.Model -> Evergreen.V20.Shared.Model
migrate_Shared_Model old =
    old |> migrate_Shared_Model_Model


migrate_Shared_Model_Model : Evergreen.V19.Shared.Model.Model -> Evergreen.V20.Shared.Model.Model
migrate_Shared_Model_Model old =
    { user = old.user |> Maybe.map migrate_Bridge_User
    , syncCode = old.syncCode
    , nextIds = old.nextIds
    , syncModel = old.syncModel |> migrate_Sync_FrontendSyncModel
    , state = old.state |> migrate_Event_State
    , menuOpen = old.menuOpen
    , version = old.version
    , toasts = old.toasts |> migrate_Components_Toast_Model
    }


migrate_Shared_Msg : Evergreen.V19.Shared.Msg -> Evergreen.V20.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V19.Shared.Msg.Msg -> Evergreen.V20.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V19.Shared.Msg.GotAdminData p0 ->
            Evergreen.V20.Shared.Msg.NoOp

        Evergreen.V19.Shared.Msg.NewUserCreated p0 ->
            Evergreen.V20.Shared.Msg.NewUserCreated (p0 |> migrate_Bridge_User)

        Evergreen.V19.Shared.Msg.AddEvent p0 ->
            Evergreen.V20.Shared.Msg.AddEvent (p0 |> migrate_Event_EventDefinition)

        Evergreen.V19.Shared.Msg.GotSyncCode p0 ->
            Evergreen.V20.Shared.Msg.GotSyncCode p0

        Evergreen.V19.Shared.Msg.GotUserData p0 ->
            Evergreen.V20.Shared.Msg.GotUserData
                { name = p0.name
                , userId = p0.userId
                , deviceId = p0.deviceId
                , deviceName = p0.deviceName
                , roles = p0.roles |> List.map migrate_Role_Role
                }

        Evergreen.V19.Shared.Msg.GotMessageFromJs p0 ->
            Evergreen.V20.Shared.Msg.GotMessageFromJs p0

        Evergreen.V19.Shared.Msg.ConnectionEstablished ->
            Evergreen.V20.Shared.Msg.ConnectionEstablished

        Evergreen.V19.Shared.Msg.GotSyncResult p0 ->
            Evergreen.V20.Shared.Msg.GotSyncResult
                { events = p0.events |> List.map migrate_Event_EventDefinition
                , lastSyncServerTime = p0.lastSyncServerTime
                }

        Evergreen.V19.Shared.Msg.UserRolesUpdated p0 ->
            Evergreen.V20.Shared.Msg.UserRolesUpdated
                { userId = p0.userId
                , roles = p0.roles |> List.map migrate_Role_Role
                }

        Evergreen.V19.Shared.Msg.SidebarToggled p0 ->
            Evergreen.V20.Shared.Msg.SidebarToggled p0

        Evergreen.V19.Shared.Msg.AddToast p0 ->
            Evergreen.V20.Shared.Msg.AddToast (p0 |> migrate_Components_Toast_Toast)

        Evergreen.V19.Shared.Msg.ToastMsg p0 ->
            Evergreen.V20.Shared.Msg.ToastMsg (p0 |> migrate_Components_Toast_Msg)


migrate_SortedEventList_Model : Evergreen.V19.SortedEventList.Model -> Evergreen.V20.SortedEventList.Model
migrate_SortedEventList_Model old =
    old |> Array.map migrate_Event_EventDefinition


migrate_Sync_FrontendSyncModel : Evergreen.V19.Sync.FrontendSyncModel -> Evergreen.V20.Sync.FrontendSyncModel
migrate_Sync_FrontendSyncModel old =
    { events = old.events |> migrate_SortedEventList_Model
    , lastSyncServerTime = old.lastSyncServerTime
    , unsyncedEventIds = old.unsyncedEventIds
    }


migrate_Types_BackendMsg : Evergreen.V19.Types.BackendMsg -> Evergreen.V20.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V19.Types.OnConnect p0 p1 ->
            Evergreen.V20.Types.OnConnect p0 p1

        Evergreen.V19.Types.NoOpBackendMsg ->
            Evergreen.V20.Types.NoOpBackendMsg

        Evergreen.V19.Types.FromFrontendWithTime p0 p1 p2 p3 ->
            Evergreen.V20.Types.FromFrontendWithTime p0 p1 (p2 |> migrate_Types_ToBackend) p3

        Evergreen.V19.Types.SyncCodeForUserCreated p0 p1 p2 p3 ->
            Evergreen.V20.Types.SyncCodeForUserCreated p0 p1 p2 p3

        Evergreen.V19.Types.AdminJobTick p0 ->
            Evergreen.V20.Types.AdminJobTick p0


migrate_Types_ToFrontend : Evergreen.V19.Types.ToFrontend -> Evergreen.V20.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V19.Types.AdminDataRequested p0 ->
            Evergreen.V20.Types.NoOp

        Evergreen.V19.Types.SyncCodeCreated p0 ->
            Evergreen.V20.Types.SyncCodeCreated p0

        Evergreen.V19.Types.SyncCodeUsed p0 ->
            Evergreen.V20.Types.SyncCodeUsed
                { name = p0.name
                , userId = p0.userId
                , deviceId = p0.deviceId
                , deviceName = p0.deviceName
                , roles = p0.roles |> List.map migrate_Role_Role
                }

        Evergreen.V19.Types.ConnectionEstablished ->
            Evergreen.V20.Types.ConnectionEstablished

        Evergreen.V19.Types.EventSyncResult p0 ->
            Evergreen.V20.Types.EventSyncResult
                { events = p0.events |> List.map migrate_Event_EventDefinition
                , lastSyncServerTime = p0.lastSyncServerTime
                }

        Evergreen.V19.Types.ListSubscriptionAdded p0 ->
            Evergreen.V20.Types.ListSubscriptionAdded p0

        Evergreen.V19.Types.ListSubscriptionFailed ->
            Evergreen.V20.Types.ListSubscriptionFailed

        Evergreen.V19.Types.UserRolesUpdated p0 ->
            Evergreen.V20.Types.UserRolesUpdated
                { userId = p0.userId
                , roles = p0.roles |> List.map migrate_Role_Role
                }


migrate_UserManagement_UserOnDeviceData : Evergreen.V19.UserManagement.UserOnDeviceData -> Evergreen.V20.UserManagement.UserOnDeviceData
migrate_UserManagement_UserOnDeviceData old =
    { userId = old.userId
    , deviceId = old.deviceId
    , deviceName = old.deviceName
    , userName = old.userName
    , roles = old.roles |> List.map migrate_Role_Role
    }
