module Evergreen.Migrate.V22 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V21.Bridge
import Evergreen.V21.Components.Toast
import Evergreen.V21.Event
import Evergreen.V21.ItemPriority
import Evergreen.V21.Layouts.Scaffold
import Evergreen.V21.Main
import Evergreen.V21.Main.Layouts.Msg
import Evergreen.V21.Main.Pages.Msg
import Evergreen.V21.Pages.Account
import Evergreen.V21.Pages.Admin.Manual
import Evergreen.V21.Pages.Admin.Menu
import Evergreen.V21.Pages.Admin.Users
import Evergreen.V21.Pages.Credits
import Evergreen.V21.Pages.Home_
import Evergreen.V21.Pages.List.ImportShared
import Evergreen.V21.Pages.Lists
import Evergreen.V21.Pages.Lists.Create
import Evergreen.V21.Pages.Lists.Edit.ListId_
import Evergreen.V21.Pages.Lists.Id_.CreateItem
import Evergreen.V21.Pages.Lists.ListId_
import Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_
import Evergreen.V21.Pages.NotFound_
import Evergreen.V21.Pages.Settings
import Evergreen.V21.Pages.Setup
import Evergreen.V21.Pages.Setup.Connect
import Evergreen.V21.Pages.Setup.NewAccount
import Evergreen.V21.Pages.SetupKnown
import Evergreen.V21.Pages.Share.ListId_
import Evergreen.V21.Role
import Evergreen.V21.Route.Path
import Evergreen.V21.Shared
import Evergreen.V21.Shared.Msg
import Evergreen.V21.Status
import Evergreen.V21.Types
import Evergreen.V21.UserManagement
import Evergreen.V22.Bridge
import Evergreen.V22.Components.Toast
import Evergreen.V22.Event
import Evergreen.V22.ItemPriority
import Evergreen.V22.Layouts.Scaffold
import Evergreen.V22.Main
import Evergreen.V22.Main.Layouts.Msg
import Evergreen.V22.Main.Pages.Msg
import Evergreen.V22.Pages.Account
import Evergreen.V22.Pages.Admin.Manual
import Evergreen.V22.Pages.Admin.Menu
import Evergreen.V22.Pages.Admin.Users
import Evergreen.V22.Pages.Credits
import Evergreen.V22.Pages.Home_
import Evergreen.V22.Pages.List.ImportShared
import Evergreen.V22.Pages.Lists
import Evergreen.V22.Pages.Lists.Create
import Evergreen.V22.Pages.Lists.Edit.ListId_
import Evergreen.V22.Pages.Lists.Id_.CreateItem
import Evergreen.V22.Pages.Lists.ListId_
import Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_
import Evergreen.V22.Pages.NotFound_
import Evergreen.V22.Pages.Settings
import Evergreen.V22.Pages.Setup
import Evergreen.V22.Pages.Setup.Connect
import Evergreen.V22.Pages.Setup.NewAccount
import Evergreen.V22.Pages.SetupKnown
import Evergreen.V22.Pages.Share.ListId_
import Evergreen.V22.Role
import Evergreen.V22.Route.Path
import Evergreen.V22.Shared
import Evergreen.V22.Shared.Msg
import Evergreen.V22.Status
import Evergreen.V22.Types
import Evergreen.V22.UserManagement
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Time


frontendModel : Evergreen.V21.Types.FrontendModel -> ModelMigration Evergreen.V22.Types.FrontendModel Evergreen.V22.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V21.Types.BackendModel -> ModelMigration Evergreen.V22.Types.BackendModel Evergreen.V22.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V21.Types.FrontendMsg -> MsgMigration Evergreen.V22.Types.FrontendMsg Evergreen.V22.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V21.Types.ToBackend -> MsgMigration Evergreen.V22.Types.ToBackend Evergreen.V22.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V21.Types.BackendMsg -> MsgMigration Evergreen.V22.Types.BackendMsg Evergreen.V22.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V21.Types.ToFrontend -> MsgMigration Evergreen.V22.Types.ToFrontend Evergreen.V22.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendMsg : Evergreen.V21.Types.FrontendMsg -> Evergreen.V22.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Bridge_User : Evergreen.V21.Bridge.User -> Evergreen.V22.Bridge.User
migrate_Bridge_User old =
    case old of
        Evergreen.V21.Bridge.Unknown ->
            Evergreen.V22.Bridge.Unknown

        Evergreen.V21.Bridge.UserOnDevice p0 ->
            Evergreen.V22.Bridge.UserOnDevice (p0 |> migrate_Bridge_UserOnDeviceData)


migrate_Bridge_UserOnDeviceData : Evergreen.V21.Bridge.UserOnDeviceData -> Evergreen.V22.Bridge.UserOnDeviceData
migrate_Bridge_UserOnDeviceData old =
    old |> migrate_UserManagement_UserOnDeviceData


migrate_Components_Toast_Msg : Evergreen.V21.Components.Toast.Msg -> Evergreen.V22.Components.Toast.Msg
migrate_Components_Toast_Msg old =
    case old of
        Evergreen.V21.Components.Toast.RemoveToast p0 ->
            Evergreen.V22.Components.Toast.RemoveToast p0


migrate_Components_Toast_Position : Evergreen.V21.Components.Toast.Position -> Evergreen.V22.Components.Toast.Position
migrate_Components_Toast_Position old =
    case old of
        Evergreen.V21.Components.Toast.TopRight ->
            Evergreen.V22.Components.Toast.TopRight

        Evergreen.V21.Components.Toast.TopLeft ->
            Evergreen.V22.Components.Toast.TopLeft

        Evergreen.V21.Components.Toast.BottomRight ->
            Evergreen.V22.Components.Toast.BottomRight

        Evergreen.V21.Components.Toast.BottomLeft ->
            Evergreen.V22.Components.Toast.BottomLeft


migrate_Components_Toast_Toast : Evergreen.V21.Components.Toast.Toast -> Evergreen.V22.Components.Toast.Toast
migrate_Components_Toast_Toast old =
    { id = old.id
    , message = old.message
    , toastType = old.toastType |> migrate_Components_Toast_ToastType
    , position = old.position |> migrate_Components_Toast_Position
    , duration = old.duration
    , withRemove = old.withRemove
    }


migrate_Components_Toast_ToastType : Evergreen.V21.Components.Toast.ToastType -> Evergreen.V22.Components.Toast.ToastType
migrate_Components_Toast_ToastType old =
    case old of
        Evergreen.V21.Components.Toast.Success ->
            Evergreen.V22.Components.Toast.Success

        Evergreen.V21.Components.Toast.Error ->
            Evergreen.V22.Components.Toast.Error

        Evergreen.V21.Components.Toast.Info ->
            Evergreen.V22.Components.Toast.Info

        Evergreen.V21.Components.Toast.Warning ->
            Evergreen.V22.Components.Toast.Warning


migrate_Event_EventData : Evergreen.V21.Event.EventData -> Evergreen.V22.Event.EventData
migrate_Event_EventData old =
    case old of
        Evergreen.V21.Event.ListCreated p0 ->
            Evergreen.V22.Event.ListCreated (p0 |> migrate_Event_ListCreatedData)

        Evergreen.V21.Event.ListUpdated p0 ->
            Evergreen.V22.Event.ListUpdated (p0 |> migrate_Event_ListUpdatedData)

        Evergreen.V21.Event.ListSharedWithUser p0 ->
            Evergreen.V22.Event.ListSharedWithUser (p0 |> migrate_Event_ListSharedWithUserData)

        Evergreen.V21.Event.ItemCreated p0 ->
            Evergreen.V22.Event.ItemCreated (p0 |> migrate_Event_ItemCreatedData)

        Evergreen.V21.Event.ItemStateChanged p0 ->
            Evergreen.V22.Event.ItemStateChanged (p0 |> migrate_Event_ItemStateChangedData)

        Evergreen.V21.Event.ItemUpdated p0 ->
            Evergreen.V22.Event.ItemUpdated (p0 |> migrate_Event_ItemUpdatedData)


migrate_Event_EventDefinition : Evergreen.V21.Event.EventDefinition -> Evergreen.V22.Event.EventDefinition
migrate_Event_EventDefinition old =
    case old of
        Evergreen.V21.Event.Event p0 p1 ->
            Evergreen.V22.Event.Event (p0 |> migrate_Event_EventMetadata)
                (p1 |> migrate_Event_EventData)


migrate_Event_EventMetadata : Evergreen.V21.Event.EventMetadata -> Evergreen.V22.Event.EventMetadata
migrate_Event_EventMetadata old =
    old


migrate_Event_ItemCreatedData : Evergreen.V21.Event.ItemCreatedData -> Evergreen.V22.Event.ItemCreatedData
migrate_Event_ItemCreatedData old =
    { itemId = old.itemId
    , itemName = old.itemName
    , itemDescription = old.itemDescription
    , itemPriority = old.itemPriority |> Maybe.map migrate_ItemPriority_ItemPriority
    }


migrate_Event_ItemStateChangedData : Evergreen.V21.Event.ItemStateChangedData -> Evergreen.V22.Event.ItemStateChangedData
migrate_Event_ItemStateChangedData old =
    old


migrate_Event_ItemUpdatedData : Evergreen.V21.Event.ItemUpdatedData -> Evergreen.V22.Event.ItemUpdatedData
migrate_Event_ItemUpdatedData old =
    { itemId = old.itemId
    , listId = old.listId
    , name = old.name
    , completed = old.completed
    , itemPriority = old.itemPriority |> Maybe.map migrate_ItemPriority_ItemPriority
    , description = old.description
    }


migrate_Event_ListCreatedData : Evergreen.V21.Event.ListCreatedData -> Evergreen.V22.Event.ListCreatedData
migrate_Event_ListCreatedData old =
    old


migrate_Event_ListSharedWithUserData : Evergreen.V21.Event.ListSharedWithUserData -> Evergreen.V22.Event.ListSharedWithUserData
migrate_Event_ListSharedWithUserData old =
    old


migrate_Event_ListUpdatedData : Evergreen.V21.Event.ListUpdatedData -> Evergreen.V22.Event.ListUpdatedData
migrate_Event_ListUpdatedData old =
    old


migrate_ItemPriority_ItemPriority : Evergreen.V21.ItemPriority.ItemPriority -> Evergreen.V22.ItemPriority.ItemPriority
migrate_ItemPriority_ItemPriority old =
    case old of
        Evergreen.V21.ItemPriority.LowItemPriority ->
            Evergreen.V22.ItemPriority.LowItemPriority

        Evergreen.V21.ItemPriority.MediumItemPriority ->
            Evergreen.V22.ItemPriority.MediumItemPriority

        Evergreen.V21.ItemPriority.HighItemPriority ->
            Evergreen.V22.ItemPriority.HighItemPriority

        Evergreen.V21.ItemPriority.HighestItemPriority ->
            Evergreen.V22.ItemPriority.HighestItemPriority


migrate_Layouts_Scaffold_Msg : Evergreen.V21.Layouts.Scaffold.Msg -> Evergreen.V22.Layouts.Scaffold.Msg
migrate_Layouts_Scaffold_Msg old =
    case old of
        Evergreen.V21.Layouts.Scaffold.CloseSidebarClicked ->
            Evergreen.V22.Layouts.Scaffold.CloseSidebarClicked

        Evergreen.V21.Layouts.Scaffold.OpenSidebarClicked ->
            Evergreen.V22.Layouts.Scaffold.OpenSidebarClicked

        Evergreen.V21.Layouts.Scaffold.NavigationClicked p0 ->
            Evergreen.V22.Layouts.Scaffold.NavigationClicked (p0 |> migrate_Route_Path_Path)

        Evergreen.V21.Layouts.Scaffold.ToastRemoveToast p0 ->
            Evergreen.V22.Layouts.Scaffold.ToastRemoveToast p0


migrate_Main_Layouts_Msg_Msg : Evergreen.V21.Main.Layouts.Msg.Msg -> Evergreen.V22.Main.Layouts.Msg.Msg
migrate_Main_Layouts_Msg_Msg old =
    case old of
        Evergreen.V21.Main.Layouts.Msg.Scaffold p0 ->
            Evergreen.V22.Main.Layouts.Msg.Scaffold (p0 |> migrate_Layouts_Scaffold_Msg)


migrate_Main_Msg : Evergreen.V21.Main.Msg -> Evergreen.V22.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V21.Main.UrlRequested p0 ->
            Evergreen.V22.Main.UrlRequested p0

        Evergreen.V21.Main.UrlChanged p0 ->
            Evergreen.V22.Main.UrlChanged p0

        Evergreen.V21.Main.Page p0 ->
            Evergreen.V22.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V21.Main.Layout p0 ->
            Evergreen.V22.Main.Layout (p0 |> migrate_Main_Layouts_Msg_Msg)

        Evergreen.V21.Main.Shared p0 ->
            Evergreen.V22.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V21.Main.Batch p0 ->
            Evergreen.V22.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Msg_Msg : Evergreen.V21.Main.Pages.Msg.Msg -> Evergreen.V22.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V21.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V22.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V21.Main.Pages.Msg.Account p0 ->
            Evergreen.V22.Main.Pages.Msg.Account (p0 |> migrate_Pages_Account_Msg)

        Evergreen.V21.Main.Pages.Msg.Admin_Manual p0 ->
            Evergreen.V22.Main.Pages.Msg.Admin_Manual (p0 |> migrate_Pages_Admin_Manual_Msg)

        Evergreen.V21.Main.Pages.Msg.Admin_Menu p0 ->
            Evergreen.V22.Main.Pages.Msg.Admin_Menu (p0 |> migrate_Pages_Admin_Menu_Msg)

        Evergreen.V21.Main.Pages.Msg.Admin_Users p0 ->
            Evergreen.V22.Main.Pages.Msg.Admin_Users (p0 |> migrate_Pages_Admin_Users_Msg)

        Evergreen.V21.Main.Pages.Msg.Credits p0 ->
            Evergreen.V22.Main.Pages.Msg.Credits (p0 |> migrate_Pages_Credits_Msg)

        Evergreen.V21.Main.Pages.Msg.List_ImportShared p0 ->
            Evergreen.V22.Main.Pages.Msg.List_ImportShared (p0 |> migrate_Pages_List_ImportShared_Msg)

        Evergreen.V21.Main.Pages.Msg.Lists p0 ->
            Evergreen.V22.Main.Pages.Msg.Lists (p0 |> migrate_Pages_Lists_Msg)

        Evergreen.V21.Main.Pages.Msg.Lists_Create p0 ->
            Evergreen.V22.Main.Pages.Msg.Lists_Create (p0 |> migrate_Pages_Lists_Create_Msg)

        Evergreen.V21.Main.Pages.Msg.Lists_Edit_ListId_ p0 ->
            Evergreen.V22.Main.Pages.Msg.Lists_Edit_ListId_ (p0 |> migrate_Pages_Lists_Edit_ListId__Msg)

        Evergreen.V21.Main.Pages.Msg.Lists_Id__CreateItem p0 ->
            Evergreen.V22.Main.Pages.Msg.Lists_Id__CreateItem (p0 |> migrate_Pages_Lists_Id__CreateItem_Msg)

        Evergreen.V21.Main.Pages.Msg.Lists_ListId_ p0 ->
            Evergreen.V22.Main.Pages.Msg.Lists_ListId_ (p0 |> migrate_Pages_Lists_ListId__Msg)

        Evergreen.V21.Main.Pages.Msg.Lists_ListId__Edit_ItemId_ p0 ->
            Evergreen.V22.Main.Pages.Msg.Lists_ListId__Edit_ItemId_ (p0 |> migrate_Pages_Lists_ListId__Edit_ItemId__Msg)

        Evergreen.V21.Main.Pages.Msg.Settings p0 ->
            Evergreen.V22.Main.Pages.Msg.Settings (p0 |> migrate_Pages_Settings_Msg)

        Evergreen.V21.Main.Pages.Msg.Setup p0 ->
            Evergreen.V22.Main.Pages.Msg.Setup (p0 |> migrate_Pages_Setup_Msg)

        Evergreen.V21.Main.Pages.Msg.Setup_Connect p0 ->
            Evergreen.V22.Main.Pages.Msg.Setup_Connect (p0 |> migrate_Pages_Setup_Connect_Msg)

        Evergreen.V21.Main.Pages.Msg.Setup_NewAccount p0 ->
            Evergreen.V22.Main.Pages.Msg.Setup_NewAccount (p0 |> migrate_Pages_Setup_NewAccount_Msg)

        Evergreen.V21.Main.Pages.Msg.SetupKnown p0 ->
            Evergreen.V22.Main.Pages.Msg.SetupKnown (p0 |> migrate_Pages_SetupKnown_Msg)

        Evergreen.V21.Main.Pages.Msg.Share_ListId_ p0 ->
            Evergreen.V22.Main.Pages.Msg.Share_ListId_ (p0 |> migrate_Pages_Share_ListId__Msg)

        Evergreen.V21.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V22.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)


migrate_Pages_Account_Msg : Evergreen.V21.Pages.Account.Msg -> Evergreen.V22.Pages.Account.Msg
migrate_Pages_Account_Msg old =
    case old of
        Evergreen.V21.Pages.Account.NoOp ->
            Evergreen.V22.Pages.Account.NoOp

        Evergreen.V21.Pages.Account.LogoutClicked ->
            Evergreen.V22.Pages.Account.LogoutClicked

        Evergreen.V21.Pages.Account.ConnectDeviceClicked ->
            Evergreen.V22.Pages.Account.ConnectDeviceClicked


migrate_Pages_Admin_Manual_Msg : Evergreen.V21.Pages.Admin.Manual.Msg -> Evergreen.V22.Pages.Admin.Manual.Msg
migrate_Pages_Admin_Manual_Msg old =
    case old of
        Evergreen.V21.Pages.Admin.Manual.NewUseridChanged p0 ->
            Evergreen.V22.Pages.Admin.Manual.NewUseridChanged p0

        Evergreen.V21.Pages.Admin.Manual.NewDeviceIdChanged p0 ->
            Evergreen.V22.Pages.Admin.Manual.NewDeviceIdChanged p0

        Evergreen.V21.Pages.Admin.Manual.NewUserNameChanged p0 ->
            Evergreen.V22.Pages.Admin.Manual.NewUserNameChanged p0

        Evergreen.V21.Pages.Admin.Manual.NewDeviceNameChanged p0 ->
            Evergreen.V22.Pages.Admin.Manual.NewDeviceNameChanged p0

        Evergreen.V21.Pages.Admin.Manual.CreateUserButtonClicked ->
            Evergreen.V22.Pages.Admin.Manual.CreateUserButtonClicked

        Evergreen.V21.Pages.Admin.Manual.ReconnectUser ->
            Evergreen.V22.Pages.Admin.Manual.ReconnectUser


migrate_Pages_Admin_Menu_Msg : Evergreen.V21.Pages.Admin.Menu.Msg -> Evergreen.V22.Pages.Admin.Menu.Msg
migrate_Pages_Admin_Menu_Msg old =
    case old of
        Evergreen.V21.Pages.Admin.Menu.NoOp ->
            Evergreen.V22.Pages.Admin.Menu.NoOp


migrate_Pages_Admin_Users_Msg : Evergreen.V21.Pages.Admin.Users.Msg -> Evergreen.V22.Pages.Admin.Users.Msg
migrate_Pages_Admin_Users_Msg old =
    case old of
        Evergreen.V21.Pages.Admin.Users.NoOp ->
            Evergreen.V22.Pages.Admin.Users.NoOp

        Evergreen.V21.Pages.Admin.Users.ToggleUserDetails p0 ->
            Evergreen.V22.Pages.Admin.Users.ToggleUserDetails p0

        Evergreen.V21.Pages.Admin.Users.RequestAdminData ->
            Evergreen.V22.Pages.Admin.Users.RequestAdminData

        Evergreen.V21.Pages.Admin.Users.GotUsers p0 ->
            Evergreen.V22.Pages.Admin.Users.GotUsers p0

        Evergreen.V21.Pages.Admin.Users.UpdateSearchQuery p0 ->
            Evergreen.V22.Pages.Admin.Users.UpdateSearchQuery p0

        Evergreen.V21.Pages.Admin.Users.DeleteUserClicked p0 ->
            Evergreen.V22.Pages.Admin.Users.DeleteUserClicked p0

        Evergreen.V21.Pages.Admin.Users.UserDeleted p0 ->
            Evergreen.V22.Pages.Admin.Users.UserDeleted p0

        Evergreen.V21.Pages.Admin.Users.ConfirmDelete p0 ->
            Evergreen.V22.Pages.Admin.Users.ConfirmDelete p0

        Evergreen.V21.Pages.Admin.Users.CancelDelete ->
            Evergreen.V22.Pages.Admin.Users.CancelDelete

        Evergreen.V21.Pages.Admin.Users.ConfirmDeleteUser p0 ->
            Evergreen.V22.Pages.Admin.Users.ConfirmDeleteUser p0


migrate_Pages_Credits_Msg : Evergreen.V21.Pages.Credits.Msg -> Evergreen.V22.Pages.Credits.Msg
migrate_Pages_Credits_Msg old =
    case old of
        Evergreen.V21.Pages.Credits.NoOp ->
            Evergreen.V22.Pages.Credits.NoOp


migrate_Pages_Home__Msg : Evergreen.V21.Pages.Home_.Msg -> Evergreen.V22.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V21.Pages.Home_.LogoutClicked ->
            Evergreen.V22.Pages.Home_.LogoutClicked


migrate_Pages_List_ImportShared_Msg : Evergreen.V21.Pages.List.ImportShared.Msg -> Evergreen.V22.Pages.List.ImportShared.Msg
migrate_Pages_List_ImportShared_Msg old =
    case old of
        Evergreen.V21.Pages.List.ImportShared.InputChanged p0 ->
            Evergreen.V22.Pages.List.ImportShared.InputChanged p0

        Evergreen.V21.Pages.List.ImportShared.ImportClicked ->
            Evergreen.V22.Pages.List.ImportShared.ImportClicked


migrate_Pages_Lists_Create_Msg : Evergreen.V21.Pages.Lists.Create.Msg -> Evergreen.V22.Pages.Lists.Create.Msg
migrate_Pages_Lists_Create_Msg old =
    case old of
        Evergreen.V21.Pages.Lists.Create.ListNameChanged p0 ->
            Evergreen.V22.Pages.Lists.Create.ListNameChanged p0

        Evergreen.V21.Pages.Lists.Create.CreateListButtonClicked ->
            Evergreen.V22.Pages.Lists.Create.CreateListButtonClicked

        Evergreen.V21.Pages.Lists.Create.GotTimeForCreateList p0 ->
            Evergreen.V22.Pages.Lists.Create.GotTimeForCreateList p0


migrate_Pages_Lists_Edit_ListId__Msg : Evergreen.V21.Pages.Lists.Edit.ListId_.Msg -> Evergreen.V22.Pages.Lists.Edit.ListId_.Msg
migrate_Pages_Lists_Edit_ListId__Msg old =
    case old of
        Evergreen.V21.Pages.Lists.Edit.ListId_.ListNameChanged p0 ->
            Evergreen.V22.Pages.Lists.Edit.ListId_.ListNameChanged p0

        Evergreen.V21.Pages.Lists.Edit.ListId_.UpdateListButtonClicked ->
            Evergreen.V22.Pages.Lists.Edit.ListId_.UpdateListButtonClicked

        Evergreen.V21.Pages.Lists.Edit.ListId_.GotTimeForUpdateList p0 ->
            Evergreen.V22.Pages.Lists.Edit.ListId_.GotTimeForUpdateList p0

        Evergreen.V21.Pages.Lists.Edit.ListId_.CopyShareLinkClicked p0 ->
            Evergreen.V22.Pages.Lists.Edit.ListId_.CopyShareLinkClicked p0


migrate_Pages_Lists_Id__CreateItem_Msg : Evergreen.V21.Pages.Lists.Id_.CreateItem.Msg -> Evergreen.V22.Pages.Lists.Id_.CreateItem.Msg
migrate_Pages_Lists_Id__CreateItem_Msg old =
    case old of
        Evergreen.V21.Pages.Lists.Id_.CreateItem.ItemNameChanged p0 ->
            Evergreen.V22.Pages.Lists.Id_.CreateItem.ItemNameChanged p0

        Evergreen.V21.Pages.Lists.Id_.CreateItem.ItemDescriptionChanged p0 ->
            Evergreen.V22.Pages.Lists.Id_.CreateItem.ItemDescriptionChanged p0

        Evergreen.V21.Pages.Lists.Id_.CreateItem.CreateItemButtonClicked ->
            Evergreen.V22.Pages.Lists.Id_.CreateItem.CreateItemButtonClicked

        Evergreen.V21.Pages.Lists.Id_.CreateItem.GotTimeForCreateItem p0 ->
            Evergreen.V22.Pages.Lists.Id_.CreateItem.GotTimeForCreateItem Evergreen.V22.Pages.Lists.Id_.CreateItem.SingleItem p0

        Evergreen.V21.Pages.Lists.Id_.CreateItem.ItemPriorityChanged p0 ->
            Evergreen.V22.Pages.Lists.Id_.CreateItem.ItemPriorityChanged p0


migrate_Pages_Lists_ListId__Edit_ItemId__Msg : Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_.Msg -> Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_.Msg
migrate_Pages_Lists_ListId__Edit_ItemId__Msg old =
    case old of
        Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_.SaveClicked ->
            Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_.SaveClicked

        Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_.NameChanged p0 ->
            Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_.NameChanged p0

        Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_.DoneClicked p0 ->
            Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_.DoneClicked p0

        Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_.GotTimeForUpdatedItem p0 ->
            Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_.GotTimeForUpdatedItem p0

        Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_.ItemPriorityChanged p0 ->
            Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_.ItemPriorityChanged p0

        Evergreen.V21.Pages.Lists.ListId_.Edit.ItemId_.ItemDescriptionChanged p0 ->
            Evergreen.V22.Pages.Lists.ListId_.Edit.ItemId_.ItemDescriptionChanged p0


migrate_Pages_Lists_ListId__Msg : Evergreen.V21.Pages.Lists.ListId_.Msg -> Evergreen.V22.Pages.Lists.ListId_.Msg
migrate_Pages_Lists_ListId__Msg old =
    case old of
        Evergreen.V21.Pages.Lists.ListId_.ItemCheckedToggled p0 p1 ->
            Evergreen.V22.Pages.Lists.ListId_.ItemCheckedToggled p0 p1

        Evergreen.V21.Pages.Lists.ListId_.GotTimeForItemCheckedToggled p0 p1 p2 ->
            Evergreen.V22.Pages.Lists.ListId_.GotTimeForItemCheckedToggled p0 p1 p2

        Evergreen.V21.Pages.Lists.ListId_.AddItemClicked ->
            Evergreen.V22.Pages.Lists.ListId_.AddItemClicked

        Evergreen.V21.Pages.Lists.ListId_.GotCurrentTime p0 ->
            Evergreen.V22.Pages.Lists.ListId_.GotCurrentTime p0

        Evergreen.V21.Pages.Lists.ListId_.ToggleArchiveClicked ->
            Evergreen.V22.Pages.Lists.ListId_.ToggleArchiveClicked


migrate_Pages_Lists_Msg : Evergreen.V21.Pages.Lists.Msg -> Evergreen.V22.Pages.Lists.Msg
migrate_Pages_Lists_Msg old =
    case old of
        Evergreen.V21.Pages.Lists.CreateDummyList ->
            Evergreen.V22.Pages.Lists.CreateDummyList

        Evergreen.V21.Pages.Lists.CreatNewListClicked ->
            Evergreen.V22.Pages.Lists.CreatNewListClicked

        Evergreen.V21.Pages.Lists.ImportSharedListClicked ->
            Evergreen.V22.Pages.Lists.ImportSharedListClicked


migrate_Pages_NotFound__Msg : Evergreen.V21.Pages.NotFound_.Msg -> Evergreen.V22.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V21.Pages.NotFound_.NoOp ->
            Evergreen.V22.Pages.NotFound_.NoOp


migrate_Pages_Settings_Msg : Evergreen.V21.Pages.Settings.Msg -> Evergreen.V22.Pages.Settings.Msg
migrate_Pages_Settings_Msg old =
    case old of
        Evergreen.V21.Pages.Settings.NoOp ->
            Evergreen.V22.Pages.Settings.NoOp


migrate_Pages_SetupKnown_Msg : Evergreen.V21.Pages.SetupKnown.Msg -> Evergreen.V22.Pages.SetupKnown.Msg
migrate_Pages_SetupKnown_Msg old =
    case old of
        Evergreen.V21.Pages.SetupKnown.NoOp ->
            Evergreen.V22.Pages.SetupKnown.NoOp


migrate_Pages_Setup_Connect_Msg : Evergreen.V21.Pages.Setup.Connect.Msg -> Evergreen.V22.Pages.Setup.Connect.Msg
migrate_Pages_Setup_Connect_Msg old =
    case old of
        Evergreen.V21.Pages.Setup.Connect.CodeInputChanged p0 ->
            Evergreen.V22.Pages.Setup.Connect.CodeInputChanged p0

        Evergreen.V21.Pages.Setup.Connect.DeviceNameChanged p0 ->
            Evergreen.V22.Pages.Setup.Connect.DeviceNameChanged p0

        Evergreen.V21.Pages.Setup.Connect.OkButtonClicked ->
            Evergreen.V22.Pages.Setup.Connect.OkButtonClicked


migrate_Pages_Setup_Msg : Evergreen.V21.Pages.Setup.Msg -> Evergreen.V22.Pages.Setup.Msg
migrate_Pages_Setup_Msg old =
    case old of
        Evergreen.V21.Pages.Setup.CreateNewAccount ->
            Evergreen.V22.Pages.Setup.CreateNewAccount

        Evergreen.V21.Pages.Setup.ConnectExistingAccount ->
            Evergreen.V22.Pages.Setup.ConnectExistingAccount

        Evergreen.V21.Pages.Setup.Logout ->
            Evergreen.V22.Pages.Setup.Logout

        Evergreen.V21.Pages.Setup.ShowNewConnectionInfo ->
            Evergreen.V22.Pages.Setup.ShowNewConnectionInfo

        Evergreen.V21.Pages.Setup.GotTime p0 ->
            Evergreen.V22.Pages.Setup.GotTime p0

        Evergreen.V21.Pages.Setup.NoOp ->
            Evergreen.V22.Pages.Setup.NoOp


migrate_Pages_Setup_NewAccount_Msg : Evergreen.V21.Pages.Setup.NewAccount.Msg -> Evergreen.V22.Pages.Setup.NewAccount.Msg
migrate_Pages_Setup_NewAccount_Msg old =
    case old of
        Evergreen.V21.Pages.Setup.NewAccount.Create ->
            Evergreen.V22.Pages.Setup.NewAccount.Create

        Evergreen.V21.Pages.Setup.NewAccount.UsernameChanged p0 ->
            Evergreen.V22.Pages.Setup.NewAccount.UsernameChanged p0

        Evergreen.V21.Pages.Setup.NewAccount.DeviceNameChanged p0 ->
            Evergreen.V22.Pages.Setup.NewAccount.DeviceNameChanged p0


migrate_Pages_Share_ListId__Msg : Evergreen.V21.Pages.Share.ListId_.Msg -> Evergreen.V22.Pages.Share.ListId_.Msg
migrate_Pages_Share_ListId__Msg old =
    case old of
        Evergreen.V21.Pages.Share.ListId_.GotListSubscriptionAdded p0 ->
            Evergreen.V22.Pages.Share.ListId_.GotListSubscriptionAdded p0

        Evergreen.V21.Pages.Share.ListId_.GotListSubscriptionFailed ->
            Evergreen.V22.Pages.Share.ListId_.GotListSubscriptionFailed

        Evergreen.V21.Pages.Share.ListId_.TimeoutSubscriptionWait ->
            Evergreen.V22.Pages.Share.ListId_.TimeoutSubscriptionWait

        Evergreen.V21.Pages.Share.ListId_.GoBackClicked ->
            Evergreen.V22.Pages.Share.ListId_.GoBackClicked


migrate_Role_Role : Evergreen.V21.Role.Role -> Evergreen.V22.Role.Role
migrate_Role_Role old =
    case old of
        Evergreen.V21.Role.User ->
            Evergreen.V22.Role.User

        Evergreen.V21.Role.Admin ->
            Evergreen.V22.Role.Admin


migrate_Route_Path_Path : Evergreen.V21.Route.Path.Path -> Evergreen.V22.Route.Path.Path
migrate_Route_Path_Path old =
    case old of
        Evergreen.V21.Route.Path.Home_ ->
            Evergreen.V22.Route.Path.Home_

        Evergreen.V21.Route.Path.Account ->
            Evergreen.V22.Route.Path.Account

        Evergreen.V21.Route.Path.Admin_Manual ->
            Evergreen.V22.Route.Path.Admin_Manual

        Evergreen.V21.Route.Path.Admin_Menu ->
            Evergreen.V22.Route.Path.Admin_Menu

        Evergreen.V21.Route.Path.Admin_Users ->
            Evergreen.V22.Route.Path.Admin_Users

        Evergreen.V21.Route.Path.Credits ->
            Evergreen.V22.Route.Path.Credits

        Evergreen.V21.Route.Path.List_ImportShared ->
            Evergreen.V22.Route.Path.List_ImportShared

        Evergreen.V21.Route.Path.Lists ->
            Evergreen.V22.Route.Path.Lists

        Evergreen.V21.Route.Path.Lists_Create ->
            Evergreen.V22.Route.Path.Lists_Create

        Evergreen.V21.Route.Path.Lists_Edit_ListId_ p0 ->
            Evergreen.V22.Route.Path.Lists_Edit_ListId_ p0

        Evergreen.V21.Route.Path.Lists_Id__CreateItem p0 ->
            Evergreen.V22.Route.Path.Lists_Id__CreateItem p0

        Evergreen.V21.Route.Path.Lists_ListId_ p0 ->
            Evergreen.V22.Route.Path.Lists_ListId_ p0

        Evergreen.V21.Route.Path.Lists_ListId__Edit_ItemId_ p0 ->
            Evergreen.V22.Route.Path.Lists_ListId__Edit_ItemId_ p0

        Evergreen.V21.Route.Path.Settings ->
            Evergreen.V22.Route.Path.Settings

        Evergreen.V21.Route.Path.Setup ->
            Evergreen.V22.Route.Path.Setup

        Evergreen.V21.Route.Path.Setup_Connect ->
            Evergreen.V22.Route.Path.Setup_Connect

        Evergreen.V21.Route.Path.Setup_NewAccount ->
            Evergreen.V22.Route.Path.Setup_NewAccount

        Evergreen.V21.Route.Path.SetupKnown ->
            Evergreen.V22.Route.Path.SetupKnown

        Evergreen.V21.Route.Path.Share_ListId_ p0 ->
            Evergreen.V22.Route.Path.Share_ListId_ p0

        Evergreen.V21.Route.Path.NotFound_ ->
            Evergreen.V22.Route.Path.NotFound_


migrate_Shared_Msg : Evergreen.V21.Shared.Msg -> Evergreen.V22.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V21.Shared.Msg.Msg -> Evergreen.V22.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V21.Shared.Msg.NewUserCreated p0 ->
            Evergreen.V22.Shared.Msg.NewUserCreated (p0 |> migrate_Bridge_User)

        Evergreen.V21.Shared.Msg.NoOp ->
            Evergreen.V22.Shared.Msg.NoOp

        Evergreen.V21.Shared.Msg.AddEvent p0 ->
            Evergreen.V22.Shared.Msg.AddEvent (p0 |> migrate_Event_EventDefinition)

        Evergreen.V21.Shared.Msg.GotSyncCode p0 ->
            Evergreen.V22.Shared.Msg.GotSyncCode p0

        Evergreen.V21.Shared.Msg.GotUserData p0 ->
            Evergreen.V22.Shared.Msg.GotUserData
                { name = p0.name
                , userId = p0.userId
                , deviceId = p0.deviceId
                , deviceName = p0.deviceName
                , roles = p0.roles |> List.map migrate_Role_Role
                }

        Evergreen.V21.Shared.Msg.GotMessageFromJs p0 ->
            Evergreen.V22.Shared.Msg.GotMessageFromJs p0

        Evergreen.V21.Shared.Msg.ConnectionEstablished ->
            Evergreen.V22.Shared.Msg.ConnectionEstablished

        Evergreen.V21.Shared.Msg.GotSyncResult p0 ->
            Evergreen.V22.Shared.Msg.GotSyncResult
                { events = p0.events |> List.map migrate_Event_EventDefinition
                , lastSyncServerTime = p0.lastSyncServerTime
                }

        Evergreen.V21.Shared.Msg.UserRolesUpdated p0 ->
            Evergreen.V22.Shared.Msg.UserRolesUpdated
                { userId = p0.userId
                , roles = p0.roles |> List.map migrate_Role_Role
                }

        Evergreen.V21.Shared.Msg.SidebarToggled p0 ->
            Evergreen.V22.Shared.Msg.SidebarToggled p0

        Evergreen.V21.Shared.Msg.AddToast p0 ->
            Evergreen.V22.Shared.Msg.AddToast (p0 |> migrate_Components_Toast_Toast)

        Evergreen.V21.Shared.Msg.ToastMsg p0 ->
            Evergreen.V22.Shared.Msg.ToastMsg (p0 |> migrate_Components_Toast_Msg)

        Evergreen.V21.Shared.Msg.NotAuthenticated ->
            Evergreen.V22.Shared.Msg.NotAuthenticated

        Evergreen.V21.Shared.Msg.StatusResponse p0 p1 ->
            Evergreen.V22.Shared.Msg.StatusResponse (p0 |> migrate_Status_Status) p1


migrate_Status_Status : Evergreen.V21.Status.Status -> Evergreen.V22.Status.Status
migrate_Status_Status old =
    case old of
        Evergreen.V21.Status.Success p0 ->
            Evergreen.V22.Status.Success p0

        Evergreen.V21.Status.Error p0 ->
            Evergreen.V22.Status.Error p0


migrate_UserManagement_UserOnDeviceData : Evergreen.V21.UserManagement.UserOnDeviceData -> Evergreen.V22.UserManagement.UserOnDeviceData
migrate_UserManagement_UserOnDeviceData old =
    { userId = old.userId
    , deviceId = old.deviceId
    , deviceName = old.deviceName
    , userName = old.userName
    , roles = old.roles |> List.map migrate_Role_Role
    }
